### PR TITLE
Issue-362: Add new styling for columns dropdown

### LINKED ISSUE #362: Update styling for `h-dropdown` + `h-table` to reflect the latest designs
**Is your feature request related to a problem? Please describe.**

- [ ] update styling to look like the latest designs
- [ ] The `dropdown` component can stay open as it does currently until a user clicks outside of the dropdown so that way a user can select multiple columns to `hide/display` before it take effect on the table

Example of Project `hide/display` columns:
image

project-hide-display-actions

**Additional context**
Related to https://github.com/hikaya-io/dots-frontend/issues/1497

This is inspired by Github projects (beta): 
image

More on github's hiding and showing feature: https://docs.github.com/en/issues/trying-out-the-new-projects-experience/customizing-your-project-views#showing-and-hiding-fields

### PR DESCRIPTION
**Pull request by Kimaiyo077**
## What issue(s) does this PR resolve?

Resolves #362 

## Considerations and implementation

Update Column reorder dropdown to separate hidden and visible columns

### How to test

1. Open Storybook
2. Select H-Table
3. Open the column dropdown and view the new design

### Test(s) added 

None

## Mentions?

@andrewtpham @ninetteadhikari

### CODE REVIEW

**Comment by andrewtpham** [comment]
@Kimaiyo077 While testing locally, after I uncheck a column the field is move to the `hidden columns` section but now if I try to select the checkbox, I'm unable to select it to display it in the table
image

Additional To Dos:
- [x] Add `data type` text section to the `h-dropdown` component. Currently the `right text area` is added in the `h-select` component which the styling can be copied from
- [ ] Move checkbox icon to the right side
- [ ] Add border radius styling

Styling reference
image

**Comment by ninetteadhikari** [comment]
Note:
- research `h-select` to see if check box can be used

**Comment by andrewtpham** [comment]
@Kimaiyo077 to add, then this can be merged:
- `While testing locally, after I uncheck a column the field is move to the hidden columns section but now if I try to select the checkbox, I'm unable to select it to display it in the table`
- upgrade hakawati version

**Comment by Kimaiyo077** [comment]
@andrewtpham The issue has been fixed and now you can select the hidden fields

**Comment by andrewtpham** [comment]
@Kimaiyo077 to add ability to drag and drop a column from shown to hidden columns and vice versa. It was said this option is easier to implement than disabling the option to drag and drop.

**Review by andrewtpham — APPROVED** [review]

**Review by ninetteadhikari — APPROVED** [review]

**Pull request merged**
