### PR TITLE
Make Save and Cancel buttons stick

### PR DESCRIPTION
**Pull request by mutebironald**
## What is the Purpose?
Briefly describe what the PR addresses
Addresses #126 By reducing the sizing of the description text area
## What was the approach?
Briefly describe the approach used to address the issue

## Are there any concerns to addressed further before or after merging this PR?
State some additional info if any. For instance running `install` or setting some environment variable(s)
This PR will have a corresponding PR on dots-frontend.
## Mentions?
Mention persons you'd like to review this PR

## Issue(s) affected?
List of issues addressed by this PR. 
#126

### CODE REVIEW

**Comment by andrewtpham** [comment]
Hi @mutebironald I reviewed the preview and dont see the dim effect on the HDrawer or any of the others? Do you how I can see this? 

This is what I currently see:
image

**Comment by andrewtpham** [comment]
This PR only partially solves the diming issue. The rest will be handled in dots-fe as stated by @mutebironald

**Comment by ninetteadhikari** [comment]
> This PR only partially solves the diming issue. The rest will be handled in dots-fe as stated by @mutebironald

@andrewtpham @mutebironald can we merge and close this issue then? if you are working on the FE on this?

**Comment by mutebironald** [comment]
> > This PR only partially solves the diming issue. The rest will be handled in dots-fe as stated by @mutebironald
> 
> @andrewtpham @mutebironald can we merge and close this issue then? if you are working on the FE on this?

@ninetteadhikari, I found a way of integrating the necessary changes in the front end PR https://github.com/hikaya-io/dots-frontend/pull/145. Let me close this one.

**Pull request merged**
