### PR TITLE
Update spreadsheet popup

### PR DESCRIPTION
**Pull request by Kimaiyo077**
## What issue(s) does this PR resolve?

Resolves partly https://github.com/hikaya-io/dots/issues/1746

## Considerations and implementation
None
## How to test

  1. Log in as ...
  2. Click on ...

## Mentions?
@andrewtpham

### CODE REVIEW

**Comment by andrewtpham** [comment]
Thanks @Kimaiyo077! Was testing locally, should the `expand record` menu item be enabled already in hakawati or is there more that will be implemented in dots once this PR is merged?
image

**Comment by Kimaiyo077** [comment]
It shouldn't be enabled because for now it will only be implemented for Indicators on Dots. I have added a prop that will enable it on the spreadsheet where we will implement the expand dialog.

**Comment by Kimaiyo077** [comment]
In fact @andrewtpham Can I just hide the add results and only show it on indicators?

**Comment by andrewtpham** [comment]
@Kimaiyo077 yes! That's a good idea to hide and only use it on indicators.

**Review by andrewtpham — APPROVED** [review]
LGTM!

**Pull request merged**
