### PR TITLE
feat: Add logic for toggling column visibility

### LINKED ISSUE #386: Allow users to view a summary of columns to `hide/display` when they click on the `Hide fields` checkbox on the toolbar
## Acceptance Criteria

GIVEN I'm a logged in user with Metrics activated

AND I click on a Project and view the Results Framework (Objectives page)

THEN I should see a toolbar (that remains fixed and not scrollable) above the spreadsheet view called `Hide fields` when all fields are displaying and `X hidden fields` when there are X number of fields that are hidden

AND when I click on `Hide field`, I should see a dropdown with a list of all the column names

AND when I un-select/select fields to display, the column should display or be hidden from the spreadsheet view including the `X number of fields` should be updated to reflect the number of fields currently hidden

Here is a walk through the functionality:
hidden-columns

## Note to dev
- Figma link (see `New toolbar` section): https://www.figma.com/file/2bizWQnCDp0r5RZzrM25jX/Dots?node-id=3827%3A12587&t=ry75BJeanuvh9uAt-1 
- The toggle component was designed around the `h-checkbox` with button styling
- A user will still be able to right-click on a specific column header and hide the selected column. Using the summary columns dropdown a user can select a column to be displayed again.
- For the toolbar, please follow the current styling on the column header in hakawati. I'm currently playing around with colors on the figma screens

### LINKED ISSUE #397: Allow a user to hide a column when they click on the column header icon OR when they right click on the column
image

### PR DESCRIPTION
**Pull request by michaelbukachi**
## What issue(s) does this PR resolve?

*List all the issues resolved by this PR*
  - Resolves #397 
  - Resolves #386

### How to test

*List the steps for others to test your changes.*
  1. Log in as ...
  2. Click on ...

## Mentions?

*@mention the people you'd like to review this PR*
@andrewtpham @ninetteadhikari

### CODE REVIEW

**Comment by ninetteadhikari** [comment]
thanks Michael this is working great! 

Is it possible to add a background color when user hovers on a column name from the dropdown. Its difficult to see which one the user is selecting.
image

**Comment by ninetteadhikari** [comment]
functionality is all there but we might need to rethink the design of the top row. it kind of looks strange with the top row width being different from table row @andrewtpham

**Comment by andrewtpham** [comment]
@michaelbukachi This is awesome! One comment:
- Can we use `el-select` instead of `el-dropdown` and achieve similar functionality? The reason why I think `el-select` would be more suited is that we can use `el-option-group` for the `visible columns` and `hidden columns` and I like when we use `multiple select` the menu stays open so you can select multiple options. 
- reference: https://element.eleme.io/#/en-US/component/select#grouping

**Comment by andrewtpham** [comment]
> functionality is all there but we might need to rethink the design of the top row. it kind of looks strange with the top row width being different from table row @andrewtpham

Added some padding to the title groups and added hover styling: 
image

**Comment by andrewtpham** [comment]
@michaelbukachi based on the call, things to look into:
- ✅  We'll continue to use `el-dropdown` component but would like the menu to stay active and open to the user so they can choose multiple columns to hide or display.
- 🔖 We would like the toolbar to align with the width of the columns displayed dynamically while still keeping the `hide column` dropdown button aligned to the right of the screen that is visible to the user. Currently, if you scroll left to right it will look like this: 
image

- ✅  We would like to add the `el-icon-check` icon to the left of each dropdown menu item. Currently I was able to add `icon="el-icon-check" to the `el-dropdown-item` but I havent been able to get the  `column type` to align to the right side of the screen: 
image
- 🔖 On the column header, can we display the right-click menu when a user clicks the column icon? 
image

**Comment by michaelbukachi** [comment]
@andrewtpham 
1 and 3 done. 2 and 4 are quite difficult to implement so they might take quite some time.

**Comment by andrewtpham** [comment]
> @andrewtpham 1 and 3 done. 2 and 4 are quite difficult to implement so they might take quite some time.

Thanks for the changes and feedback @michaelbukachi 

I've created them as separate tickets:
- https://github.com/hikaya-io/hakawati/issues/401
- https://github.com/hikaya-io/hakawati/issues/402

**Review by andrewtpham — APPROVED** [review]

**Pull request merged**
