### PR TITLE
wip: Add spreadsheet component

### PR DESCRIPTION
**Pull request by michaelbukachi**
## What is the Purpose?
This PR adds a new spreadsheet component
- [x] Add basic styling
- [ ] Allow sortable columns
- [ ] Allow column reordering and save position
- [x] Add new input '+' icon that sticks to the bottom of the last row when table is NOT long 
- [x] allow users to add data per column for new row (similar to adding new project)
- [x] allow users to do in-line edit of data (same as `h-table`)
- [ ] allow users to hide/show column and save the selection
- [x] if column is a known set of options, display a dropdown: https://github.com/hikaya-io/hakawati/issues/241
- [x] Add validation errors for relevant input types
- [ ] add view/edit event/hook

## What was the approach?
Briefly describe the approach used to address the issue

## Are there any concerns to addressed further before or after merging this PR?
State some additional info if any. For instance running `install` or setting some environment variable(s)

## Mentions?
Mention persons you'd like to review this PR

## Issue(s) affected?
List of issues addressed by this PR.

### CODE REVIEW

**Comment by andrewtpham** [comment]
@michaelbukachi The data types we should support in the spreadsheet are:

- [x] `integer`
- [x] `decimal`
- [x] `boolean` (this is a boolean and can display `TRUE` or `FALSE`). This is displayed as a `checkbox`.
- [x] `category` (this is a dropdown from another object. For example the project object has the status field as a related object)
- [x] `text`
- [x] `date`
- [x] `percentage`

We can these in the future:
- [ ] `geolocation` (decimal format with comma-separated, space-separated, or `semi-colon-separated`)
- [ ] `url`

**Comment by ninetteadhikari** [comment]
Validations:
- instead of not allowing users to add incorrect input, expected behavior would be for the user add incorrect input and show an error message

**Comment by andrewtpham** [comment]
@michaelbukachi updated the designs to display an entire row when the `add icon` is selected: spreadsheet-add-row

**Comment by ninetteadhikari** [comment]
Note:
- Date component: currently the html date is not showing. need to check why this is failing and alternatively maybe use element ui datepicker or another component
- For date format we can following the project list page format YYYY-MM-DD. We can keep it flexible so we can change the format later if needed.
- Add `data type` in the column header

**Comment by andrewtpham** [comment]
Note:
- use `h-datepicker` for date columns
- use `h-select` for category columns

**Review by andrewtpham — APPROVED** [review]
Tested and it looks great! Well done 🙇‍♂️

**Comment by andrewtpham** [comment]
@michaelbukachi if you're okay, let's merge this and then we can open a separate PR to add the following:
- Allow sortable columns
- Allow column reordering and save position
- Allow users to hide/show column and save the selection
- Add view/edit event/hook (not sure if its done yet) - add logic to `double-click` functionality

**Comment by michaelbukachi** [comment]
@andrewtpham Sure thing. No problem.

**Pull request merged**
